[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "AutoHackOS"
authors = [{name = "Team AutoHackOS", email = "security@autohackos.com"}]
dynamic = ["version", "description"]
